import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:inbodysimpletracker/data/services/local_video_service_mobile.dart';

void main() {
  late Directory temporaryDirectory;
  late LocalVideoService service;
  setUp(() async {
    temporaryDirectory = await Directory.systemTemp.createTemp(
      'checkpoint_test_',
    );
    service = LocalVideoService(
      documentsDirectory: () async => temporaryDirectory,
    );
  });
  tearDown(() async => temporaryDirectory.delete(recursive: true));

  test('destination paths sanitize filenames and reject invalid IDs', () {
    expect(
      LocalVideoService.destinationReference('safe_id', '../../My video.mov'),
      'training_videos/safe_id/My_video.mov',
    );
    expect(
      LocalVideoService.sanitizeFileName(r'C:\Downloads\clip.mp4'),
      'clip.mp4',
    );
    expect(LocalVideoService.sanitizeFileName('..'), 'video');
    expect(LocalVideoService.sanitizeFileName('${'a' * 200}.mov').length, 120);
    expect(
      () => LocalVideoService.destinationReference('../escape', 'video'),
      throwsArgumentError,
    );
  });

  test(
    'copies generated bytes, resolves managed file and removes empty directory',
    () async {
      // Small generated data, never an actual training video or a repository fixture.
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2, 3, 4]);
      final reference = await service.copyVideo(
        checkpointId: 'id',
        sourcePath: source.path,
        originalFileName: 'My video.mp4',
      );
      expect(reference, 'training_videos/id/My_video.mp4');
      final resolved = await service.resolvePath(reference);
      expect(await File(resolved!).readAsBytes(), [1, 2, 3, 4]);
      await service.deleteVideo(reference);
      expect(await service.resolvePath(reference), isNull);
      expect(
        await Directory(
          '${temporaryDirectory.path}/training_videos/id',
        ).exists(),
        isFalse,
      );
      expect(await source.exists(), isTrue);
      await service.deleteVideo(reference);
    },
  );

  test(
    'missing and untrusted paths do not access files outside managed storage',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsString('keep');
      for (final reference in [
        source.path,
        '../source.tmp',
        'training_videos/id/../source.tmp',
        'training_videos/id/..',
        'training_videos/id\\source.tmp',
        '',
      ]) {
        expect(await service.resolvePath(reference), isNull);
        await service.deleteVideo(reference);
      }
      expect(await source.readAsString(), 'keep');
      expect(
        await service.resolvePath('training_videos/missing/file.mov'),
        isNull,
      );
    },
  );

  test('copy failure removes the newly created checkpoint directory', () async {
    await expectLater(
      service.copyVideo(
        checkpointId: 'id',
        sourcePath: '${temporaryDirectory.path}/missing',
        originalFileName: 'clip.mov',
      ),
      throwsA(isA<FileSystemException>()),
    );
    expect(
      await Directory('${temporaryDirectory.path}/training_videos/id').exists(),
      isFalse,
    );
  });
}
