import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:inbodysimpletracker/data/services/local_video_service_mobile.dart';
import 'package:inbodysimpletracker/data/services/local_video_copy_exception.dart';

void main() {
  late Directory temporaryDirectory;
  late LocalVideoService service;
  setUp(() async {
    temporaryDirectory = await Directory.systemTemp.createTemp(
      'checkpoint_test_',
    );
    service = LocalVideoService(
      documentsDirectory: () async => temporaryDirectory,
    );
  });
  tearDown(() async => temporaryDirectory.delete(recursive: true));

  test('destination paths sanitize filenames and reject invalid IDs', () {
    expect(
      LocalVideoService.destinationReference('safe_id', '../../My video.mov'),
      'training_videos/safe_id/My_video.mov',
    );
    expect(
      LocalVideoService.sanitizeFileName(r'C:\Downloads\clip.mp4'),
      'clip.mp4',
    );
    expect(LocalVideoService.sanitizeFileName('..'), 'video');
    expect(LocalVideoService.sanitizeFileName('${'a' * 200}.mov').length, 120);
    expect(
      () => LocalVideoService.destinationReference('../escape', 'video'),
      throwsArgumentError,
    );
  });

  test(
    'copies generated bytes, resolves managed file and removes empty directory',
    () async {
      // Small generated data, never an actual training video or a repository fixture.
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2, 3, 4]);
      final reference = await service.copyVideo(
        checkpointId: 'id',
        sourcePath: source.path,
        originalFileName: 'My video.mp4',
      );
      expect(reference, 'training_videos/id/My_video.mp4');
      final resolved = await service.resolvePath(reference);
      expect(await File(resolved!).readAsBytes(), [1, 2, 3, 4]);
      await service.deleteVideo(reference);
      expect(await service.resolvePath(reference), isNull);
      expect(
        await Directory(
          '${temporaryDirectory.path}/training_videos/id',
        ).exists(),
        isFalse,
      );
      expect(await source.exists(), isTrue);
      await service.deleteVideo(reference);
    },
  );

  test(
    'missing and untrusted paths do not access files outside managed storage',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsString('keep');
      for (final reference in [
        source.path,
        '../source.tmp',
        'training_videos/id/../source.tmp',
        'training_videos/id/..',
        'training_videos/id\\source.tmp',
        '',
      ]) {
        expect(await service.resolvePath(reference), isNull);
        await service.deleteVideo(reference);
      }
      expect(await source.readAsString(), 'keep');
      expect(
        await service.resolvePath('training_videos/missing/file.mov'),
        isNull,
      );
    },
  );

  test('copy failure removes the newly created checkpoint directory', () async {
    await expectLater(
      service.copyVideo(
        checkpointId: 'id',
        sourcePath: '${temporaryDirectory.path}/missing',
        originalFileName: 'clip.mov',
      ),
      throwsA(isA<FileSystemException>()),
    );
    expect(
      await Directory('${temporaryDirectory.path}/training_videos/id').exists(),
      isFalse,
    );
  });

  test(
    'binds references to IDs and re-resolves Documents after restart',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2, 3]);
      final first = await service.copyVideo(
        checkpointId: 'first',
        sourcePath: source.path,
        originalFileName: 'clip.MOV',
      );
      final second = await service.copyVideo(
        checkpointId: 'second',
        sourcePath: source.path,
        originalFileName: 'clip.MOV',
      );
      final restarted = LocalVideoService(
        documentsDirectory: () async => temporaryDirectory,
      );
      expect(
        await restarted.resolvePath(first, checkpointId: 'first'),
        isNotNull,
      );
      expect(
        await restarted.resolvePath(second, checkpointId: 'first'),
        isNull,
      );
      await restarted.deleteVideo(second, checkpointId: 'first');
      expect(
        await restarted.resolvePath(second, checkpointId: 'second'),
        isNotNull,
      );
      expect(await source.readAsBytes(), [1, 2, 3]);
    },
  );

  test(
    'concurrent copies reserve a destination without overwriting the winner',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([4, 5, 6]);
      Future<Object> copy() async {
        try {
          return await service.copyVideo(
            checkpointId: 'same',
            sourcePath: source.path,
            originalFileName: 'clip.mp4',
          );
        } catch (error) {
          return error;
        }
      }

      final results = await Future.wait([copy(), copy()]);
      expect(results.whereType<String>().length, 1);
      expect(
        results.whereType<Exception>().length +
            results.whereType<Error>().length,
        1,
      );
      final path = await service.resolvePath(
        results.whereType<String>().single,
      );
      expect(await File(path!).readAsBytes(), [4, 5, 6]);
    },
  );

  test(
    'checks actual length, empty sources, and allowed extensions before copying',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2, 3, 4]);
      await expectLater(
        service.copyVideo(
          checkpointId: 'large',
          sourcePath: source.path,
          originalFileName: 'clip.mov',
          maxSizeBytes: 3,
        ),
        throwsArgumentError,
      );
      await expectLater(
        service.copyVideo(
          checkpointId: 'extension',
          sourcePath: source.path,
          originalFileName: 'clip.exe',
        ),
        throwsArgumentError,
      );
      await source.writeAsBytes([]);
      await expectLater(
        service.copyVideo(
          checkpointId: 'empty',
          sourcePath: source.path,
          originalFileName: 'clip.mov',
        ),
        throwsArgumentError,
      );
      expect(
        await Directory('${temporaryDirectory.path}/training_videos').exists(),
        isFalse,
      );
    },
  );

  test(
    'relative references resolve against a restored Documents root',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2]);
      final originalRoot = Directory(
        '${temporaryDirectory.path}/original_documents',
      );
      final firstService = LocalVideoService(
        documentsDirectory: () async => originalRoot,
      );
      final reference = await firstService.copyVideo(
        checkpointId: 'id',
        sourcePath: source.path,
        originalFileName: 'clip.mp4',
      );
      final restoredRoot = await originalRoot.rename(
        '${temporaryDirectory.path}/restored_documents',
      );
      final restartedService = LocalVideoService(
        documentsDirectory: () async => restoredRoot,
      );
      final path = await restartedService.resolvePath(
        reference,
        checkpointId: 'id',
      );
      expect(path, startsWith(restoredRoot.path));
      expect(await File(path!).readAsBytes(), [1, 2]);
    },
  );

  test(
    'rejects and cleans a source changed between length validation and copying',
    () async {
      final source = File('${temporaryDirectory.path}/source.tmp');
      await source.writeAsBytes([1, 2]);
      var rootCalls = 0;
      final changingService = LocalVideoService(
        documentsDirectory: () async {
          if (rootCalls++ == 0) await source.writeAsBytes([1, 2, 3]);
          return temporaryDirectory;
        },
      );
      await expectLater(
        changingService.copyVideo(
          checkpointId: 'id',
          sourcePath: source.path,
          originalFileName: 'clip.mp4',
        ),
        throwsStateError,
      );
      expect(
        await Directory(
          '${temporaryDirectory.path}/training_videos/id',
        ).exists(),
        isFalse,
      );
    },
  );

  test('reports cleanup failure for an owned partial destination', () async {
    final source = File('${temporaryDirectory.path}/source.tmp');
    await source.writeAsBytes([1, 2]);
    var rootCalls = 0;
    final changingService = LocalVideoService(
      documentsDirectory: () async {
        if (rootCalls++ > 0) {
          throw StateError('Documents unavailable during cleanup');
        }
        await source.writeAsBytes([]);
        return temporaryDirectory;
      },
    );
    await expectLater(
      changingService.copyVideo(
        checkpointId: 'id',
        sourcePath: source.path,
        originalFileName: 'clip.mp4',
      ),
      throwsA(isA<LocalVideoCopyException>()),
    );
    expect(
      await File(
        '${temporaryDirectory.path}/training_videos/id/clip.mp4',
      ).exists(),
      isTrue,
    );
  });
}
