// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVvlrbSGDXwHKfU_XpccYYauRsN89Hkw',
    appId: '1:148923167758:web:2c6ffffb5e78ec06f6f85f',
    messagingSenderId: '148923167758',
    projectId: 'inbodysimpletracker',
    authDomain: 'inbodysimpletracker.firebaseapp.com',
    storageBucket: 'inbodysimpletracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyXEtEjt53gSVt3oFsPkjRl58OhTe4DjY',
    appId: '1:148923167758:android:9408e1ec8660ae9af6f85f',
    messagingSenderId: '148923167758',
    projectId: 'inbodysimpletracker',
    storageBucket: 'inbodysimpletracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0M1iaPt2wo59h5og9wdr2d_V3eH0kJhc',
    appId: '1:148923167758:ios:edbc0d2cf0c36b98f6f85f',
    messagingSenderId: '148923167758',
    projectId: 'inbodysimpletracker',
    storageBucket: 'inbodysimpletracker.firebasestorage.app',
    iosBundleId: 'com.example.inbodysimpletracker',
  );
}
